Repository euphony-io/order-with, pull requests merged in 2022-07, with the labels that each got.

#2 [SETTING] Initial Settings #1
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: setting

#5 Update build.gradle and .gitignore #1
  .gitignore
  app/build.gradle
Labels: setting

#8 [SETTING] Update .gitignore, build.gradle and Manifest #1
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: setting

#6 [FEAT] [SETTING] Building Database and Update build.gradle
  app/build.gradle
  app/src/main/java/com/euphonyio/orderwith/data/AppDatabase.kt
  app/src/main/java/com/euphonyio/orderwith/data/DBUtil.kt
  app/src/main/java/com/euphonyio/orderwith/data/dao/MenuDao.kt
  app/src/main/java/com/euphonyio/orderwith/data/dao/OrderDao.kt
  app/src/main/java/com/euphonyio/orderwith/data/dao/OrderMenuDao.kt
  app/src/main/java/com/euphonyio/orderwith/data/dto/Menu.kt
  app/src/main/java/com/euphonyio/orderwith/data/dto/Order.kt
  app/src/main/java/com/euphonyio/orderwith/data/dto/OrderMenu.kt
  app/src/main/java/com/euphonyio/orderwith/data/dto/OrderMenuItem.kt
Labels: feat, setting

#10 [FEAT] 메인화면, 메뉴 등록 다이얼로그 UI 구현
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/euphonyio/orderwith/CustomerActivity.kt
  app/src/main/java/com/euphonyio/orderwith/MainActivity.kt
  app/src/main/java/com/euphonyio/orderwith/StoreActivity.kt
  app/src/main/res/drawable-v24/customer.png
  app/src/main/res/drawable-v24/shops.png
  app/src/main/res/values/strings.xml
  build.gradle
  settings.gradle
Labels: feat

#12 [FEAT] CustomerActivity 구현 #4
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/euphonyio/orderwith/CustomerActivity.kt
  app/src/main/res/drawable/ic_minus_count.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: feat

#14 [SETTING] 최신 euphony aar파일 적용
  .gitignore
  app/src/main/java/com/euphonyio/orderwith/CustomerActivity.kt
  app/src/main/java/com/euphonyio/orderwith/MainActivity.kt
  libs/euphony-0.7.1.6.aar
Labels: chore, setting

#16 [FEAT] Menu Dialog와 Room 연결 (#13)
  app/build.gradle
  app/src/main/java/com/euphonyio/orderwith/MainActivity.kt
  app/src/main/java/com/euphonyio/orderwith/StoreActivity.kt
  app/src/main/java/com/euphonyio/orderwith/data/AppDatabase.kt
  app/src/main/java/com/euphonyio/orderwith/data/DBUtil.kt
  app/src/main/java/com/euphonyio/orderwith/data/dao/MenuDao.kt
  app/src/main/java/com/euphonyio/orderwith/data/dao/OrderDao.kt
  app/src/main/java/com/euphonyio/orderwith/data/dao/OrderMenuDao.kt
Labels: feat

#18 [FEAT] Permission 요청 및 MenuList관련 업데이트
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/euphonyio/orderwith/CustomerActivity.kt
  app/src/main/java/com/euphonyio/orderwith/MainActivity.kt
  app/src/main/java/com/euphonyio/orderwith/model/MenuItem.kt
  app/src/main/java/com/euphonyio/orderwith/viewModel/CustomerViewModel.kt
Labels: feat, setting

#19 [FEAT] Store_Activity 및 UI구현
  app/build.gradle
  app/libs/euphony_0.7.1.6.aar
  app/src/androidTest/java/com/euphonyio/orderwith/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/euphonyio/orderwith/RequestCodeEnum.kt
  app/src/main/java/com/euphonyio/orderwith/StoreActivity.kt
  app/src/main/java/com/euphonyio/orderwith/data/AppDatabase.kt
  app/src/main/java/com/euphonyio/orderwith/data/DBUtil.kt
  app/src/main/java/com/euphonyio/orderwith/data/dao/OrderDao.kt
  app/src/main/java/com/euphonyio/orderwith/data/dao/OrderMenuDao.kt
  app/src/main/res/values/strings.xml
Labels: feat, build, chore, test

#24 [FIX] 삭제된 권한 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/euphonyio/orderwith/MainActivity.kt
Labels: fix, chore

#25 [FIX] StoreActivity 수정
  app/src/main/java/com/euphonyio/orderwith/CustomerActivity.kt
  app/src/main/java/com/euphonyio/orderwith/StoreActivity.kt
Labels: feat, fix

#26 [FIX] listen 코드 추가, AddMenuDialog 수정
  app/src/main/java/com/euphonyio/orderwith/StoreActivity.kt
Labels: feat
